services:
  - type: web
    plan: free
    name: apprvd-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/ichwanhs96/apprvd.git
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apprvd-app-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false

databases:
  - name: apprvd-app-db
    plan: free