services:
  - type: web
    plan: free
    name: apprvd-app
    runtime: python
    repo: https://github.com/ichwanhs96/apprvd.git
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn -w 4 -b 0.0.0.0:8000 myapp:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apprvd-app-db
          property: connectionString

databases:
  - name: apprvd-app-db
    plan: free