version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "27015:27017"
    volumes:
      - db_data:/data/db
    env_file:
      - .env

volumes:
  db_data: