version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      # - db
      - pgdb

  # db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.db
  #   ports:
  #     - "27015:27017"
  #   volumes:
  #     - db_data:/data/db
  #   env_file:
  #     - .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  pgdb:
    build:
      context: .
      dockerfile: Dockerfile.pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdb_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGDB_NAME}
      POSTGRES_USER: ${PGDB_USER}
      POSTGRES_PASSWORD: ${PGDB_PASSWORD}

volumes:
  db_data:
  pgdb_data: