# Use the official MongoDB image
FROM mongo:latest

# Install MongoDB shell tools
RUN apt-get update && apt-get install -y mongodb-clients

# Set the working directory in the container
WORKDIR /data/db

# Copy the init script into the container
COPY init-mongo.sh /init-mongo.sh

# Grant execute permissions for the script
RUN chmod +x /init-mongo.sh

# Expose the default MongoDB port
EXPOSE 27017

# Use the init script as the entrypoint
ENTRYPOINT ["/init-mongo.sh"]