version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "27015:27017"
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $(DB_USER)
      MONGO_INITDB_ROOT_PASSWORD: $(DB_PASSWORD)
    command: ["sh", "-c", "echo $DB_USER && echo $DB_PASSWORD"]

volumes:
  db_data: